BEGIN;

DROP TABLE
    IF EXISTS "category",
    "recipe",
    "ingredient",
    "recipe_has_ingredient",
    "instruction",
    "category_has_recipe",
    "user",
    "comment",
    "favorite",
    "note";

CREATE TABLE
    IF NOT EXISTS "category" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL DEFAULT '',
        "image_url" TEXT,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

CREATE TABLE
    IF NOT EXISTS "recipe" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL DEFAULT '',
        "image_url" TEXT NOT NULL DEFAULT '',
        "preparation_time" TEXT NOT NULL DEFAULT '',
        "cooking_time" TEXT,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

CREATE TABLE
    IF NOT EXISTS "category_has_recipe" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "category_id" integer NOT NULL REFERENCES "category"("id") ON DELETE CASCADE,
        "recipe_id" integer NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

CREATE TABLE
    IF NOT EXISTS "ingredient" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL DEFAULT '',
        "image_url" TEXT,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

CREATE TABLE
    IF NOT EXISTS "recipe_has_ingredient" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "quantity" TEXT NOT NULL DEFAULT '',
        "recipe_id" integer NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE,
        "ingredient_id" integer NOT NULL REFERENCES "ingredient"("id") ON DELETE CASCADE,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

CREATE TABLE
    IF NOT EXISTS "instruction" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL DEFAULT '',
        "description" TEXT NOT NULL DEFAULT '',
        "recipe_id" integer NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

CREATE TABLE
    IF NOT EXISTS "user" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "email" TEXT NOT NULL DEFAULT '',
        "user_name" TEXT NOT NULL DEFAULT '',
        "password" TEXT NOT NULL DEFAULT '',
        "avatar_url" TEXT,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

CREATE TABLE
    IF NOT EXISTS "comment" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "content" TEXT NOT NULL DEFAULT '',
        "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
        "recipe_id" integer NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

CREATE TABLE
    IF NOT EXISTS "favorite" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
        "recipe_id" integer NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

CREATE TABLE
    IF NOT EXISTS "note" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "content" TEXT NOT NULL DEFAULT '',
        "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
        "recipe_id" integer NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMPTZ
    );

COMMIT;